### ISSUE TITLE
Screenshot results in black screen on wayland - possible solution

### ISSUE THREAD

**Issue by htl-leonding** [2324-4bhif-syp/2324-4bhif-syp-project-franklyn#8]
According to https://forum.manjaro.org/t/help-taking-a-screencapture-in-java-it-used-to-work/21620/3 
It could be possible to use the screenshot functionality of javafx, because awt doesn't work with wayland.
https://openjfx.io/javadoc/21/javafx.graphics/javafx/scene/robot/Robot.html

```
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-graphics</artifactId>
    <version>21.0.1</version>
</dependency>
```

**Comment by aichingert** [comment]
This got fixed by the new openbox client.
